TOKEN = "6367532329:AAEyb8Uyot8Zj-wBbAyy-ZjJpt4JIeIKGvY"
ADMIN_ID = 5736655322

DATA_FOLDER = "data"
ACC_FILE = f"{DATA_FOLDER}/acc.txt"
SOLD_FILE = f"{DATA_FOLDER}/sold_acc.txt"
USER_FILE = f"{DATA_FOLDER}/users.json"
BACKUP_FOLDER = f"{DATA_FOLDER}/backup"
